### ISSUE TITLE
Bad development

### ISSUE THREAD

**Issue by jamieduk** [yodigi7/quiplash#40]
Bad development, i like simple just the files no setups required no 8080 bs just extract and play, it should use a mysqli database and php and js, jquery not strange files and java editors or ide's should be required, i also like having things in folders this seems it requires the whole site just for this 1 game, i could be wrong but there must be a simpler way this should be build a more standardised method!

**Comment by yodigi7** [comment]
Actually, currently have it up and running using github pages and heroku, will update the README to reflect this.

**Comment by yodigi7** [comment]
Added the Quickstart to the README: https://github.com/yodigi7/quiplash/blob/master/README.md#quickstart

> In order to access the GameMaster (the shared screen for all contenders) go to: https://yodigi7.github.io/quiplash/gamemaster/. The access point for each contender is https://yodigi7.github.io/quiplash/contender/. Give it a few seconds to boot up as it is likely sleeping on Heroku, it should take ~30 seconds for the server to spin up and start working.
